apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:/Lhc2KCZAuc55r8okN8xLRPj5ckM6F78My4s+a2bUjAjDHZig1y7sRFcCbTj+pyYD7Sq83RI5gTl/mGriPcaAHKoMDdJF7EW9g1AKjHMVnxCKdvRsiNKVEUmB/EpI4I0oYKkAm8chlZFAdZyJSEBF89LTqS56uwtpKizLFb0BF7xkvbVE4d4GVpqtbftjJ2RF3thZMlYrHT6Ny+jPK8tJMLv9N16MdYneEOauHDmdQshdGfrUmsgo5Dj+5qrZLnVidsJUk6eVyl52h00puD6q49uKCgha0QNSzvDBokEnvz2rX/dfKyTxazTrr4=,iv:W/rAUOvNGga3xvQFiXiEArjF/iCGDBEahDrVDJC85/k=,tag:6OHo7v+Ge+ZOGSZXGHefqA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1mfaglelt0vuphrd66us4ppudtdgk09akaq6v2vktlwmh0mssje6qwc0cse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaUowZXUvTjlvOXJxTmsy
            V0VXN3NmQ3hvc0RjTEJNZ1NYaXJCTUdvTnhNCjlScVZ4TkgxSUhiMVN6VW5qcjJP
            aVltOUVWWWs4UExBRmdKQ2Rkby9xYWcKLS0tIENjWS9DdnRNS0lWWkFiZks2d0pQ
            VitRM0svOWt2YlpiWVhWT3NwLzRnV2cKm1hKoSN0UG4jvSIbGC+Qn9oypciX+eS6
            e6epC5ca0lnNwgoGWyFt+PlJ6aCd2XbT/IGE56P/ASy8++4pPuC1Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T05:07:35Z"
    mac: ENC[AES256_GCM,data:859zu7nnAbdEezgDqTimNgR0EUZP7/v92w40FL5Ku1ualNkQnJcRQ7PmX1vonlfRCjFTwUXGop9tcwieLAm9JD5hI0S0CqWqQAhidpDxB/FfhKzdEq9mgDcMbIOpDfYVONxQeEW8jRnSJCfWwdeTyV79IEAS4LiZ6cpKtR9zuLI=,iv:At3zzA+tMUzifdQHB/sljq365/izkDuQd55kxeSco2Q=,tag:jdUuIjXCDGTHM55blKw40w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
