apiVersion: v1
data:
    password: ENC[AES256_GCM,data:4XIwzeZ56A0=,iv:AwguHahxOF8Xdke39kzY4Nq5gNxOnttp3FXUkxDp2BY=,tag:fYQ9KijzYP50h16quh43dg==,type:str]
    user: ENC[AES256_GCM,data:TaWexXqhyiQ=,iv:BmrAE2/3u2ft1adPHjqv1Zsz0I6kb2mdUH08WK1+SHo=,tag:yJiVasy+7qYLg9u7JJtqlA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1mfaglelt0vuphrd66us4ppudtdgk09akaq6v2vktlwmh0mssje6qwc0cse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SEpya0pFWXNnOVhER3E5
            d1ZIWWVsY0dycnF2MVo0dGhpRnRWMmFmUGtZCklranpPMjROTkRVdVNFZ1FqaVc0
            NHQ5Syt3dVlCWGt3dmsybEltNVhTU2MKLS0tIFNLV0Z5R3QyVzgrb1F5L01KSkZD
            K29mYnozUm5qNUlzWkZ0QTZuNng2eEkKSlRLnEGje1uq4QyhlF+M8/DSQOK5/pu/
            aZbIK19yybzgqmf3ZyJ78io8wIhOwwIWTXPWqHVTe7n7XVMYoKKGNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T04:04:34Z"
    mac: ENC[AES256_GCM,data:DpLhykZB05E+Why6nPtRRBSYsfIKg5e+4rewxHeW2UvGbNnpWSp3gyd2shmlGeuPJmWnnY0eixze3z0ggDsX5cFfXJRtrOyp2UqgaDL0e5y7NP7i9XuJB23A3edsbdyrrYZHE5z4orpaCiXyaHQqVYlph3ZLPTBjkBCj8WNB2UA=,iv:NL5yHZhh18okCNv7U0OOKrXvMF8uZuQMpxVRaAT/qNY=,tag:D1BxWf9cLklurDDSE6OoSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
